### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by acrosman** [acrosman/snowmakery#1]
The ReadMe file could use more than a little editing. It is short on details, has no screenshots, and could generally just be made better.

**Comment by hnishal** [comment]
I would love to work on this, describe me how you want it

**Comment by aakhtar3** [comment]
@acrosman I can polish up the README.md

**Comment by aakhtar3** [comment]
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.
